from team_finder.constants import USER_PHONE_MAX_LENGTH

USER_PHONE_LOCAL_PREFIX = "8"
USER_PHONE_COUNTRY_PREFIX = "+7"
USER_PHONE_DIGITS_COUNT = USER_PHONE_MAX_LENGTH - 1

AVATAR_WIDTH = 200
AVATAR_HEIGHT = 200
AVATAR_FONT_SIZE = 96
AVATAR_TEXT_Y_SHIFT = -8
AVATAR_TEXT_ANCHOR = (0, 0)
AVATAR_TEXT_COLOR = (255, 255, 255)
AVATAR_FILE_FORMAT = "PNG"

AVATAR_BG_COLOR_BLUE = (58, 95, 145)
AVATAR_BG_COLOR_GREEN = (74, 122, 85)
AVATAR_BG_COLOR_PURPLE = (127, 97, 163)
AVATAR_BG_COLOR_BROWN = (140, 98, 57)
AVATAR_BG_COLOR_TEAL = (73, 115, 122)

AVATAR_BG_COLORS = [
    AVATAR_BG_COLOR_BLUE,
    AVATAR_BG_COLOR_GREEN,
    AVATAR_BG_COLOR_PURPLE,
    AVATAR_BG_COLOR_BROWN,
    AVATAR_BG_COLOR_TEAL,
]

AVATAR_FONT_PATH = "static/fonts/Neue_Haas_Grotesk_Display_Pro_75_Bold.otf"
AVATAR_FONT_FALLBACK = "arial.ttf"
AVATAR_DEFAULT_LETTER = "U"

USERS_PAGE_SIZE = 12
